class UsernameTakenException(Exception):
	def __init__(self):
		pass

class AlreadyAPasswordWithThatNameException(Exception):
	def __init__(self):
		pass
